language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  code_climate:
    repo_token: CODECLIMATE_REPO_TOKEN
before_script:
- npm install -g istanbul codeclimate-test-reporter mocha
script:
- xvfb-run mocha
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then mocha;
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then npm run coverage;
  fi
after_script:
  - codeclimate-test-reporter < coverage/lcov.info